# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Run automatically after the Android CI release finishes
  workflow_run:
    workflows: [ "Android CI" ]
    branches: [ "master" ]
    types: [ "completed" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Website
        run: |
          echo -e "Running build script with Python..."
          python deploy.py
          echo -e "Script complete."
        shell: bash
        working-directory: ./HelpPage/scripts/
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build JavaDoc using Dokka
        run: |
          ./gradlew :TeamCode:dokkaHtml --no-daemon
          mv ./TeamCode/build/dokka/html ./HelpPage/opt/javadoc
      - name: Download the latest APK
        run: |
          mkdir -p ./HelpPage/opt/apk/bin
          cd ./HelpPage/opt/apk/bin
          curl -LO https://github.com/XaverianTeamRobotics/FtcRobotController/releases/download/latest-ci-build/TeamCode-debug.apk
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload final build
          path: './HelpPage/opt'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
